#!/usr/bin/env bash

set -eu

# Check necessary commands exist.
{ command -v mime-construct && command -v ansi2txt && command -v ansi2html; } >/dev/null || {
	echo 'Missing commands'
	echo 'Need mime-construct, ansi2txt and ansi2html in PATH'
	exit 1
} >&2

# Implement an interface that means this could be used as a drop-in replacement
# for `mail`.
check_empty=
header_args=()
while getopts 'a:b:c:dEfIiNnr:s:u:v' opt; do
	case "$opt" in
		a)	header_args+=(--header "$OPTARG");;
		b)	header_args+=(--bcc "$OPTARG");;
		c)	header_args+=(--cc "$OPTARG");;
		E)	check_empty=YesPlease;;
		r)	header_args+=(--header "From: $OPTARG");;
		s)	header_args+=(--subject "$OPTARG");;
		d|f|I|i|N|n|u|v)
			printf '%s is not implemented!\n' "$opt" >&2
			exit 1
			;;
	esac
done
shift "$(( OPTIND - 1 ))"
for arg; do
	header_args+=(--to "$arg")
done

tempfile="$(mktemp)"
trap 'rm -f -- "$tempfile"' EXIT

cat >"$tempfile"

[[ "$check_empty" && ! -s "$tempfile" ]] && exit 0

mime-construct "${header_args[@]}" --multipart 'multipart/alternative' --file <(ansi2txt <"$tempfile") --type 'text/html' --file <(ansi2html -w <"$tempfile")
